In [3]:
import tensorflow as tf

In [4]:
a=tf.constant(1) #1이라는 상수를 a라는 이름의 노드로 정의
print(a) #a노드의 정보가 출력 스칼라는 0차원이라
# a.eval() 

Tensor("Const:0", shape=(), dtype=int32)


In [8]:
sess=tf.Session()
print(sess.run(a)) #a노드를(그래프를) 실행하라
sess.close()

1


### 동일 구문

In [9]:
with tf.Session() as sess:
    print(sess.run(a))
    print(a.eval())#세션이 만들어지기 전에는 오류 발생 보통 with구문 내에서 사용 가능하지만 그냥 sees.run(a)가 일반적

1
1


In [12]:
x=tf.constant(35,name='x')
y=tf.Variable(x+5, name='y')
gvi=tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(gvi) #변수들이 초기화(개시)된다
    print(sess.run(y))

40


In [21]:
a=tf.placeholder('float')
b=tf.placeholder('float')
y=tf.multiply(a,b)
z=tf.add(y,y)
elems=tf.Variable([1.0,2.0,2.0,2.0,])
#elems까지 정의끝
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())#변수있으면 반드시 따라와야하는 구문
    #feed
    print(sess.run(y,feed_dict={a:3, b:3}))
    print(sess.run(z,feed_dict={a:4, b:3}))
    #fetch
    print(sess.run(elems))

9.0
24.0
[1. 2. 2. 2.]


In [25]:
input1=tf.placeholder(tf.float32)
input2=tf.placeholder(tf.float32)
output=tf.multiply(input1,input2)
with tf.Session() as sess:
    print(sess.run([output],feed_dict={input1:7.,input2:2.})) #두 개 이상 실행시 대괄호로
    

[14.0]


In [34]:
#  x=tf.placeholder([None,3]) 
#None:shape이 아직 정해지지 않은 상태, 굳이 행이나 열을 세지 않아도 됨
x=tf.placeholder("float", [2,None]) #float32:4byte
y=x*2
with tf.Session() as sess:
    print(sess.run(x, feed_dict={x:[[5,2,1],[2,4,6]]}))
    res=sess.run(y,feed_dict={x:[[5,2,1],[2,4,6]]}) #x,y와 -달리 정의된 노드 아님

[[5. 2. 1.]
 [2. 4. 6.]]


In [37]:
tf.set_random_seed(777)
norm=tf.random_normal([2,3], mean=-1,stddev=4, seed=777)
print(norm)
with tf.Session() as sess:
    print(sess.run(norm))
# sess=tf.Session()
# print(sess.run(norm))

Tensor("random_normal_2:0", shape=(2, 3), dtype=float32)
[[-1.834207    2.523636    5.3439183 ]
 [ 0.18537867  1.7630076   6.0473523 ]]


In [38]:
c=tf.constant([[1,2],[3,4],[5,6]])
shuff=tf.random_shuffle(c)
sess=tf.Session()
print(sess.run(shuff))

[[1 2]
 [5 6]
 [3 4]]
